version: '3.8'

services:
  realitycheck-app:
    build: .
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped

  # Optional: Add a reverse proxy for API calls to avoid CORS
  proxy:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./proxy.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
    depends_on:
      - realitycheck-app

  # Optional: Redis for caching API responses
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

volumes:
  redis_data: